githubConfigUrl: https://github.com/wsd-team-dev
githubConfigSecret: k8s-runner-secret
runnerScaleSetName: "solvians-runner"
minRunners: 2
containerMode:
  type: kubernetes
template:
  spec:
    initContainers:
    - name: kube-init
      image: ghcr.io/actions/actions-runner:latest
      command: ["sudo", "chown", "-R", "1001:123", "/home/runner/_work"]
      volumeMounts:
      - name: work
        mountPath: /home/runner/_work
    containers:
    - name: runner
      image: "ghcr.io/wsd-team-devops/github-runner:2.317.0-1.0.0"
      command:
      - /home/runner/run.sh
      env:
      - name: ACTIONS_RUNNER_CONTAINER_HOOKS
        value: /home/runner/k8s/index.js
      - name: ACTIONS_RUNNER_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
        value: "false"
      volumeMounts:
      - name: work
        mountPath: /home/runner/_work
    volumes:
    - name: work
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "longhorn"
            resources:
              requests:
                storage: 5Gi